// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Core.Tren", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Trenler", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Başkent Express"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Doğu Express"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Çukurova Express"
                        },
                        new
                        {
                            Id = 4,
                            Name = "İst-Ank YHT"
                        });
                });

            modelBuilder.Entity("Core.Wagon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Capasity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TrenId")
                        .HasColumnType("int");

                    b.Property<int>("fullseat")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrenId");

                    b.ToTable("Wagons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capasity = 100,
                            Name = "Vagon 1",
                            TrenId = 1,
                            fullseat = 64
                        },
                        new
                        {
                            Id = 2,
                            Capasity = 90,
                            Name = "Vagon 2",
                            TrenId = 1,
                            fullseat = 75
                        },
                        new
                        {
                            Id = 3,
                            Capasity = 110,
                            Name = "Vagon 3",
                            TrenId = 1,
                            fullseat = 61
                        },
                        new
                        {
                            Id = 4,
                            Capasity = 100,
                            Name = "Vagon 4",
                            TrenId = 1,
                            fullseat = 88
                        },
                        new
                        {
                            Id = 5,
                            Capasity = 100,
                            Name = "Vagon 1",
                            TrenId = 2,
                            fullseat = 64
                        },
                        new
                        {
                            Id = 6,
                            Capasity = 70,
                            Name = "Vagon 2",
                            TrenId = 2,
                            fullseat = 70
                        },
                        new
                        {
                            Id = 7,
                            Capasity = 110,
                            Name = "Vagon 3",
                            TrenId = 2,
                            fullseat = 51
                        },
                        new
                        {
                            Id = 8,
                            Capasity = 120,
                            Name = "Vagon 4",
                            TrenId = 2,
                            fullseat = 84
                        },
                        new
                        {
                            Id = 9,
                            Capasity = 90,
                            Name = "Vagon 1",
                            TrenId = 3,
                            fullseat = 74
                        },
                        new
                        {
                            Id = 10,
                            Capasity = 95,
                            Name = "Vagon 2",
                            TrenId = 3,
                            fullseat = 70
                        },
                        new
                        {
                            Id = 11,
                            Capasity = 110,
                            Name = "Vagon 3",
                            TrenId = 3,
                            fullseat = 81
                        },
                        new
                        {
                            Id = 12,
                            Capasity = 120,
                            Name = "Vagon 4",
                            TrenId = 3,
                            fullseat = 88
                        },
                        new
                        {
                            Id = 13,
                            Capasity = 90,
                            Name = "Vagon 1",
                            TrenId = 4,
                            fullseat = 65
                        },
                        new
                        {
                            Id = 14,
                            Capasity = 90,
                            Name = "Vagon 2",
                            TrenId = 4,
                            fullseat = 79
                        },
                        new
                        {
                            Id = 15,
                            Capasity = 100,
                            Name = "Vagon 3",
                            TrenId = 4,
                            fullseat = 61
                        },
                        new
                        {
                            Id = 16,
                            Capasity = 100,
                            Name = "Vagon 4",
                            TrenId = 4,
                            fullseat = 82
                        });
                });

            modelBuilder.Entity("Core.Wagon", b =>
                {
                    b.HasOne("Core.Tren", "Tren")
                        .WithMany("Wagons")
                        .HasForeignKey("TrenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tren");
                });

            modelBuilder.Entity("Core.Tren", b =>
                {
                    b.Navigation("Wagons");
                });
#pragma warning restore 612, 618
        }
    }
}
